version: '3.7'

services:
  prometheus:
    command: |
      --config.file=/etc/prometheus/prometheus.dev.yml
      --log.level=debug

  grafana:
    environment:
      GF_DEFAULT_INSTANCE_NAME:
      GF_SERVER_DOMAIN:
      GF_SERVER_ROOT_URL:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_ANONYMOUS_ENABLED:
      GF_AUTH_ANONYMOUS_ORG_NAME:
      GF_AUTH_GITHUB_ENABLED:
      GF_AUTH_GITHUB_ALLOW_SIGN_UP:
      GF_AUTH_GITHUB_CLIENT_ID:
      GF_AUTH_GITHUB_CLIENT_SECRET:
      GF_AUTH_GITHUB_SCOPES: user:email,read:org
      GF_AUTH_GITHUB_AUTH_URL: https://github.com/login/oauth/authorize
      GF_AUTH_GITHUB_TOKEN_URL: https://github.com/login/oauth/access_token
      GF_AUTH_GITHUB_API_URL: https://api.github.com/user
      GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS:
      GF_ANALYTICS_REPORTING_ENABLED:
      GF_RENDERING_SERVER_URL: http://localhost:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - grafana-storage:/var/lib/grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    expose:
      - 8081
    ports:
      - 8081:8081

volumes:
  prometheus-storage:
  grafana-storage: