version: '3.7'

services:
  listener:
    build:
      context: .
    restart: unless-stopped
    expose:
      - 2489
    ports:
      - "2489:2489"
    volumes:
      - cargo-cache:/home/rust/.cargo
      - target-cache:/home/rust/src/target
    env_file:
      - .env.prod

  prometheus:
    command: |
      --config.file=/etc/prometheus/prometheus.prod.yml
      --log.level=debug

  grafana:
    environment:
      GF_DEFAULT_INSTANCE_NAME:
      GF_SERVER_DOMAIN:
      GF_SERVER_ROOT_URL:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_ANONYMOUS_ENABLED:
      GF_AUTH_ANONYMOUS_ORG_NAME:
      GF_AUTH_GITHUB_ENABLED:
      GF_AUTH_GITHUB_ALLOW_SIGN_UP:
      GF_AUTH_GITHUB_CLIENT_ID:
      GF_AUTH_GITHUB_CLIENT_SECRET:
      GF_AUTH_GITHUB_SCOPES: user:email,read:org
      GF_AUTH_GITHUB_AUTH_URL: https://github.com/login/oauth/authorize
      GF_AUTH_GITHUB_TOKEN_URL: https://github.com/login/oauth/access_token
      GF_AUTH_GITHUB_API_URL: https://api.github.com/user
      GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS:
      GF_ANALYTICS_REPORTING_ENABLED:

volumes:
  cargo-cache:
  target-cache: