{
 "title": "Wordle Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "game",
    "query": {
     "query": "label_values(wordle_stats_games, game)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(wordle_stats_games, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "1/6 Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_games{score=\"1\", game=\"$game\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "2/6 Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_games{score=\"2\", game=\"$game\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "3/6 Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_games{score=\"3\", game=\"$game\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "4/6 Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_games{score=\"4\", game=\"$game\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "5/6 Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_games{score=\"5\", game=\"$game\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "6/6 Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_games{score=\"6\", game=\"$game\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "X/6 Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_games{score=\"X\", game=\"$game\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Game Scores / Minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(wordle_stats_games{game=\"$game\"}[1m])",
     "legendFormat": "{{score}}/6"
    }
   ]
  },
  {
   "title": "Guess Distribution",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wordle_stats_games{game=\"$game\", instance=\"$instance\"}",
     "legendFormat": "{{score}}/6"
    }
   ]
  },
  {
   "title": "Total Tweets Received",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_tweet_count{ instance=\"$instance\" })"
    }
   ]
  },
  {
   "title": "Tweets Received Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "increase(wordle_stats_tweet_count{ instance=\"$instance\" }[1m])",
     "legendFormat": "{{score}}/6"
    }
   ]
  },
  {
   "title": "Dark Mode Users",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_dark_mode{ game=\"$game\" })"
    }
   ]
  },
  {
   "title": "Hard Mode Users",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wordle_stats_hard_mode{ game=\"$game\" })"
    }
   ]
  },
  {
   "title": "Game Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "expr": "increase(wordle_stats_games{instance=\"$instance\", game=\"$game\"}[1d])",
     "legendFormat": "{{score}}/6"
    }
   ]
  }
 ]
}